#!/usr/bin/env zsh

set -e

clone() {
  if [ ! -d $2 ] ; then
    git clone git@github.com:$1/$2
  fi
}


clone cruftbusters backstage

clone cruftbusters devpod

clone cruftbusters dotcom

find . -name .devcontainer.onStartCommand -exec bash -c "echo === running {} ; time eval {}" \;

exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
