#!/usr/bin/env zsh

git config --global include.path .gitconfig.host
git config --global core.editor nvim
git config --global init.defaultBranch main
git config --global pull.rebase true
git config --global push.autoSetupRemote true

git clone git@github.com:cruftbusters/devpod.git

git clone git@github.com:cruftbusters/dotcom.git

exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
