#!/usr/bin/env zsh

git config --global include.path /root/.gitconfig.host

git config --global core.editor nvim
git config --global init.defaultBranch main
git config --global pull.rebase true
git config --global push.autoSetupRemote true

workspace=/workspace

mkdir $workspace

cd $workspace

# devpod

git clone git@github.com:cruftbusters/devpod.git

ln -sf $workspace/devpod/nginx.conf /etc/nginx/nginx.conf

ln -sf $workspace/devpod/index.html /usr/share/nginx/html/index.html

nginx

# dotcom

git clone git@github.com:cruftbusters/dotcom

cd $workspace/dotcom

COREPACK_ENABLE_DOWNLOAD_PROMPT=0 pnpm -r install

screen -d -m -S home-dev pnpm -F home dev
screen -d -m -S home-test pnpm -F home exec vitest --ui --api 5174
screen -d -m -S home-e2e pnpm -F home exec playwright test --ui --ui-port 5175

cd -

/bin/zsh
