#!/usr/bin/env zsh

tag=cruftbusters/devpod

podman build -f containerfile -t $tag .

if [ "$SSH_AUTH_SOCK" = "" ]; then
  eval $(ssh-agent)
  ssh-add
fi

podman run -it --rm \
  -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
  -p 8080:8080 \
  -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
  -v $HOME/.gitconfig:/root/.gitconfig:ro \
  -v $HOME/.ssh/known_hosts:/root/.ssh/known_hosts \
  $tag
