#!/usr/bin/env zsh

tag=cruftbusters/devpod

podman build -f containerfile -t $tag .

if [ "$SSH_AUTH_SOCK" = "" ]; then
  eval $(ssh-agent)
  ssh-add
fi

podman run \
  --interactive \
  --tty \
  --rm \
  --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
  --publish 8080:8080 \
  --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
  --volume $HOME/.gitconfig:/root/.gitconfig:ro \
  --volume $HOME/.ssh/known_hosts:/root/.ssh/known_hosts \
  $tag
