#!/usr/bin/env zsh

tag=cruftbusters/devpod

podman build -f containerfile -t $tag .

if [ "$SSH_AUTH_SOCK" = "" ]; then
  eval $(ssh-agent)
  ssh-add
fi

if [ -f cidfile ] ; then
  podman start $(cat cidfile)
else

  podman run \
    --cidfile cidfile \
    --detach \
    --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
    --publish 8080:8080 \
    --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
    --volume $HOME/.gitconfig:/root/.gitconfig.host:ro \
    --volume $HOME/.ssh/known_hosts:/root/.ssh/known_hosts \
    $tag

fi
