FROM mcr.microsoft.com/playwright:v1.49.1-noble

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y build-essential less nginx screen unzip zsh
RUN apt-get clean

RUN npm install --global corepack

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN usermod -s /bin/zsh root
RUN sed -i 's/robbyrussell/aussiegeek/' /root/.zshrc

RUN curl -sfLO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
RUN tar -C /opt -xzf nvim-linux-x86_64.tar.gz && \
    rm nvim-linux-x86_64.tar.gz && \
    ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin
RUN echo EDITOR=nvim >> /root/.zshrc

RUN git clone https://github.com/LazyVim/starter /root/.config/nvim

RUN echo 'vim.o.shell = "zsh"' >> /root/.config/nvim/lua/config/options.lua

RUN nvim --headless "+Lazy! sync" +qa

COPY .devcontainer/entrypoint /root/entrypoint
CMD /root/entrypoint
